name: 有效性检测

on:
  schedule:
    - cron: '10 23 * * *' # 每天 23:10 自動運行
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Upgrade pip and install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium requests futures eventlet opencv-python Beautifulsoup4 translate termcolor func_timeout replace input opencc pypinyin pytz tqdm

      - name: TXT 轉為 M3U
        run: python ${{ github.workspace }}/IPTV/txtTOm3u.py

      - name: 檢測與去重
        run: python ${{ github.workspace }}/IPTV/V4检测优选.py
          
      - name: 過濾中文頻道
        run: python ${{ github.workspace }}/IPTV/zho頻道過濾.py
        
      - name: 過濾港澳台頻道
        run: python ${{ github.workspace }}/IPTV/gat頻道過濾.py
       
      - name: 過濾成人頻道
        run: python ${{ github.workspace }}/IPTV/adult頻道過濾.py

      - name: Get current date
        run: echo "DATE=$(date +'%Y-%m-%d %H:%M:%S CST')" >> $GITHUB_ENV

      - name: Update README
        run: echo "過濾重覆及有效性自動檢測 IPTV $DATE" > README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@126.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto update: $DATE" || echo "No changes to commit"
          git push
